[build]
  command = "npm run build"
  publish = "build"

[context.deploy-preview]
  command = "npm run build"
  publish = "build"

[context.merge]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
